// POPDSP JavaScript Document
var tollfree='+1-888-888-8888';
var m1='****Dont Restart Your Computer **** \n MAC Detected ZEUS Virus, The Infections detected, indicate some recent downloads on the computer which in turn has created problems on the computer.Call technical support '+tollfree+' and share this code B2957E to the Agent to Fix This. \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n';
var m2='Warning: ZEUS VIRUS DETECTED !!!\n\n Customer Service: '+tollfree+'  (TOLL-FREE)\n\nA Suspicious TROJAN Was Trying to Access Your Logins, Banking Details & Tracking Your Internet Activity.\n\nYour Firewall has failed to protect and is damaged. Your Accounts May be Suspended Until You Take an Action.\n\nYour Personal Information May Have Leaked. IMMEDIATE RESPONSE REQUIRED\n\nYour Hard Disk Has A Trojan Virus! Please Do Not Try to Fix Manually, It May Crash Your Data.\n\nConsequently, we are performing additional security checks to verify system security.\n\nPlease Visit Your Nearest MAC Service Center OR Call Help Desk\n\n---------------------------------------------------------\nCustomer Service: '+tollfree+'  (TOLL-FREE)\n---------------------------------------------------------\n\n\n\n\n********** IMMEDIATE RESPONSE REQUIRED **********\n\nPlease contact network administration to rectify the issue.\nPlease do not open internet browser for your security issue to avoid data corruption on your registery of your operating system. Please contact network administration department at '+tollfree+' (TOLL-FREE)\n\nVirus Info:\nA Trojan horse, or Trojan, in computing is a non-self-replicating type of malware program containing malicious code that, when executed, carries out actions determined by the nature of the Trojan, typically causing loss or theft of data, and possible system harm. The term is derived from the story of the wooden horse used to trick defenders of Troy into taking concealed warriors into their city in ancient Greece, because computer Trojans often employ a form of social engineering, presenting themselves as routine, useful, or interesting in order to persuade victims to install them on their computers.\n\nA Trojan often acts as a backdoor, contacting a controller which can then have unauthorized access to the affected computer. The Trojan and backdoors are not themselves easily detectable, but if they carry out significant computing or communications activity may cause the computer to run noticeably slowly. Malicious programs are classified as Trojans if they do not attempt to inject themselves into other files (computer virus) or otherwise propagate themselves (worm).\n\nA computer may host a Trojan via a malicious program a user is duped into executing files or browsing internet.\nPlease contact network administration department at '+tollfree+' (TOLL-FREE)\n\n';
function myFunction(){}

function rtclickcheck(keyp)
	{ 	if (navigator.appName == "Netscape" && keyp.which == 3){}

		if (navigator.appVersion.indexOf("MSIE") != -1 && event.button == 2){}
	}
	document.onmousedown = rtclickcheck;
